apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: resource-management
spec:
  selector:
    matchLabels:
      name: redis-pod
      app: resource-management
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        name: redis-pod
        app: resource-management
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          imagePullPolicy: IfNotPresent