apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: resource-management
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30009
  selector:
    name: redis-pod
    app: resource-management