apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-service
  namespace: default
  labels:
    app: kafka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-service
  template:
    metadata:
      labels:
        name: kafka-service
        app: kafka-service
    spec:
      hostname: kafka-service
      containers:
        - name: kafka-service
          image: wurstmeister/kafka:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-cluster1:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
          ports:
            - containerPort: 9092

---