apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: default
  labels:
    app: kafka-service
spec:
  type: NodePort
  selector:
    app: kafka-service
  ports:
    - name: kafka-service
      protocol: TCP
      port: 9092
      targetPort: 9092