apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    name: mongodb-deployment
    app: resource-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-pod
      name: resource-management
  template:
    metadata:
      labels:
        app: mongodb-pod
        name: resource-management
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password