apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb-service
    app: resource-management
spec:
  type: NodePort
  selector:
    app: mongodb-pod
    name: resource-management
  ports:
    - protocol: TCP
      port: 27017
      nodePort: 30010