apiVersion: v1
kind: Service
metadata:
  name: rms-service
spec:
  type: NodePort
  selector:
    name: rms-pod
    app: resource-management
  ports:
    - protocol: TCP
      port: 8013
      targetPort: 8013
      nodePort: 30008